# Generated by Django 5.2.1 on 2025-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_order_alter_item_price_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'Рубли'), ('usd', 'Доллары')], default='rub', max_length=5),
        ),
    ]
